version: '3.9'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - pg-db
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
  pg-db:
    container_name: pg-db
    image: postgres
    restart: always
    expose:
      - "5432"
    env_file:
      - ./database/env_vars
    volumes:
      - ./database/data:/var/lib/postgresql/data
