version: '3.9'

services:
  backend:
    image: python-django
    ports:
      - 8000:8000
    depends_on:
      - database
  database:
    image: postgres
    env_file:
      - ./database/env_vars
    volumes:
      - ./database/data:docker-entrypoint-initdb.d:ro
      - pg_project:/var/lib/postgresql/data
volumes:
  pg_project: