# Generated by Django 4.1.1 on 2022-09-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comments_signature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='Comment',
        ),
    ]
